<?php
/**
 * uninstall.php — executed when the user deletes the plugin via WP admin.
 *
 * Cleans up:
 *   - options (config, version, audit log meta)
 *   - change-ledger DB table
 *   - audit log files in wp-content/uploads/rolepod-wp-audit/
 *   - recovery guardian mu-plugin (v2.6+)
 *   - recovery transients (recent fatals, safe mode)
 *
 * Theme snapshots in wp-content/uploads/rolepod-wp-theme-snapshots/ are
 * preserved by default — they may have been generated by other tools or
 * carry value beyond this plugin's lifecycle. User can delete manually.
 */

declare(strict_types=1);

if (!defined('WP_UNINSTALL_PLUGIN')) {
    exit;
}

// Remove options
delete_option('rolepod_wp_version');
delete_option('rolepod_wp_config');
delete_option('rolepod_wp_audit_log');
delete_option('rolepod_wp_changes_schema_version');
delete_option('rolepod_wp_safe_mode');

// Drop v2.3 change-ledger table
require_once __DIR__ . '/src/Audit/ChangeLedger.php';
\Rolepod\Wp\Audit\ChangeLedger::uninstall();

// v2.6 — remove recovery guardian mu-plugin
require_once __DIR__ . '/src/Guardian.php';
\Rolepod\Wp\Guardian::remove();

// v2.6 — clear recovery transients
delete_transient('rolepod_wp_recovery_recent_fatals');

// Remove audit log directory
$uploadDir = wp_upload_dir();
if (is_array($uploadDir) && !empty($uploadDir['basedir'])) {
    $auditDir = trailingslashit($uploadDir['basedir']) . 'rolepod-wp-audit';
    if (is_dir($auditDir)) {
        $files = glob($auditDir . '/*.log');
        if (is_array($files)) {
            foreach ($files as $f) {
                @unlink($f);
            }
        }
        @rmdir($auditDir);
    }
}
