<?php
declare(strict_types=1);

namespace Rolepod\Wp\Security;

/**
 * One-time pair token for the v1.2 "Quick start" flow.
 *
 *   Generated by an admin via the Setup Wizard.
 *   Redeemed by the wplab Node MCP (via `rolepod_wp_pair`) once.
 *   On redeem the companion mints a real Application Password under the
 *   issuing admin's user, named `wplab-pair-<timestamp>` so the admin can
 *   revoke it from profile.php at any time.
 *
 * Storage: SHA-256 hash + metadata in wp_options under one row per token.
 * TTL: 60 minutes. Single-use enforced atomically on redeem (delete-then-act).
 * Rate-limit: see Generate/Redeem endpoint guards.
 *
 * Token wire format: `rolepod_wp_pair_<48 hex chars>` (256 bits entropy).
 */
final class PairToken
{
    public const OPTION_PREFIX = 'rolepod_wp_pair_';
    public const TTL_SECONDS = 3600;
    public const TOKEN_PREFIX = 'rolepod_wp_pair_';

    /**
     * Issue a new token for the given admin user. Returns the raw token to
     * show in the wizard once; the wp_options row stores only the SHA-256.
     */
    public static function issue(int $userId): string
    {
        $raw = self::TOKEN_PREFIX . bin2hex(random_bytes(24));
        $hash = hash('sha256', $raw);
        $payload = [
            'user_id' => $userId,
            'issued_at' => time(),
            'expires_at' => time() + self::TTL_SECONDS,
        ];
        add_option(self::OPTION_PREFIX . $hash, $payload, '', false);
        return $raw;
    }

    /**
     * Atomically redeem a token. Returns the issuing user_id on success,
     * or null if the token is unknown, expired, or already redeemed.
     */
    public static function redeem(string $rawToken): ?int
    {
        if (strpos($rawToken, self::TOKEN_PREFIX) !== 0) {
            return null;
        }
        $hash = hash('sha256', $rawToken);
        $key = self::OPTION_PREFIX . $hash;
        $payload = get_option($key, null);
        if (!is_array($payload)) {
            return null;
        }
        // Delete first — guarantees single-use even under concurrent calls.
        delete_option($key);
        if (($payload['expires_at'] ?? 0) < time()) {
            return null;
        }
        $userId = (int) ($payload['user_id'] ?? 0);
        return $userId > 0 ? $userId : null;
    }

    /**
     * Sweep expired tokens. Called opportunistically on issue() to keep
     * wp_options from accumulating dead rows. Returns the count removed.
     */
    public static function sweepExpired(): int
    {
        global $wpdb;
        $like = $wpdb->esc_like(self::OPTION_PREFIX) . '%';
        $rows = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT option_name, option_value FROM {$wpdb->options} WHERE option_name LIKE %s",
                $like
            )
        );
        if (!is_array($rows)) {
            return 0;
        }
        $now = time();
        $removed = 0;
        foreach ($rows as $row) {
            $payload = maybe_unserialize($row->option_value);
            if (!is_array($payload) || ($payload['expires_at'] ?? 0) < $now) {
                delete_option($row->option_name);
                $removed += 1;
            }
        }
        return $removed;
    }

    /** Count active (non-expired) tokens for a specific admin — for rate-limit. */
    public static function countActiveFor(int $userId): int
    {
        global $wpdb;
        $like = $wpdb->esc_like(self::OPTION_PREFIX) . '%';
        $rows = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT option_value FROM {$wpdb->options} WHERE option_name LIKE %s",
                $like
            )
        );
        if (!is_array($rows)) {
            return 0;
        }
        $now = time();
        $count = 0;
        foreach ($rows as $row) {
            $payload = maybe_unserialize($row->option_value);
            if (
                is_array($payload)
                && (int) ($payload['user_id'] ?? 0) === $userId
                && ($payload['expires_at'] ?? 0) >= $now
            ) {
                $count += 1;
            }
        }
        return $count;
    }

    public static function ttlSeconds(): int
    {
        return self::TTL_SECONDS;
    }
}
